NameColor: 'f'
SpecialTime: 5
DisplayPosition:
- Position: '-38,19,213'
  Type: '5,10'
- Position: '-36,19,213'
  Type: '5,10'
- Position: '-34,19,213'
  Type: '1,5,10'
- Position: '-32,19,213'
  Type: '5,10'
- Position: '-30,19,213'
  Type: '5,10'
- Position: '-38,21,213'
  Type: '10'
- Position: '-36,21,213'
  Type: '10'
- Position: '-34,21,213'
  Type: '10'
- Position: '-32,21,213'
  Type: '10'
- Position: '-30,21,213'
  Type: '10'
Button:
- Position: '-35,19,218'
  Count: 1
  Special: false
- Position: '-34,19,218'
  Count: 5
  Special: false
- Position: '-33,19,218'
  Count: 10
  Special: false
- Position: '-38,19,221'
  Count: 1
  Special: true